let hello_joke = [
  {
    error: false,
    amount: 10,
    jokes: [
      {
        category: "Programming",
        type: "twopart",
        setup: "Why are Assembly programmers always soaking wet?",
        delivery: "They work below C-level.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        safe: true,
        id: 263,
        lang: "en",
      },
      {
        category: "Programming",
        type: "single",
        joke: "Saying that Java is nice because it works on every OS is like saying that anal sex is nice because it works on every gender.",
        flags: {
          nsfw: true,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: true,
        },
        id: 30,
        safe: false,
        lang: "en",
      },
      {
        category: "Programming",
        type: "single",
        joke: "The glass is neither half-full nor half-empty, the glass is twice as big as it needs to be.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 23,
        safe: true,
        lang: "en",
      },
      {
        category: "Programming",
        type: "twopart",
        setup: "Why do they call it hyper terminal?",
        delivery: "Too much Java.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 225,
        safe: true,
        lang: "en",
      },
      {
        category: "Programming",
        type: "single",
        joke: "Have a great weekend!\nI hope your code behaves the same on Monday as it did on Friday.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 44,
        safe: true,
        lang: "en",
      },
      {
        category: "Programming",
        type: "twopart",
        setup: "What is a dying programmer's last program?",
        delivery: "Goodbye, world!",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 55,
        safe: true,
        lang: "en",
      },
      {
        category: "Programming",
        type: "single",
        joke: "Knock knock.\nWho's there?\nRecursion.\nRecursion who?\nKnock knock.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 179,
        safe: true,
        lang: "en",
      },
      {
        category: "Programming",
        type: "twopart",
        setup:
          "So what's a set of predefined steps the government might take to preserve the environment?",
        delivery: "An Al-Gore-ithm.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 51,
        safe: true,
        lang: "en",
      },
      {
        category: "Programming",
        type: "twopart",
        setup: "What do you call a developer who doesn't comment code?",
        delivery: "A developer.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 14,
        safe: true,
        lang: "en",
      },
      {
        category: "Programming",
        type: "twopart",
        setup: "Why did the programmer quit his job?",
        delivery: "Because he didn't get arrays.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 16,
        safe: true,
        lang: "en",
      },
    ],
  },

  {
    error: false,
    amount: 10,
    jokes: [
      {
        category: "Programming",
        type: "twopart",
        setup: "Why are modern programming languages so materialistic?",
        delivery: "Because they are object-oriented.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 21,
        safe: true,
        lang: "en",
      },
      {
        category: "Dark",
        type: "twopart",
        setup:
          "What do Ted Bundy and the Space Shuttle Columbia have in common?",
        delivery: "They both left bodies in four states.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: true,
        },
        id: 153,
        safe: false,
        lang: "en",
      },
      {
        category: "Dark",
        type: "twopart",
        setup: "What part of a vegetable are you not supposed to eat?",
        delivery: "The wheelchair.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 152,
        safe: false,
        lang: "en",
      },
      {
        category: "Programming",
        type: "single",
        joke: "Being a self-taught developer is almost the same as being a cut neck chicken because you have no sense of direction in the beginning.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 183,
        safe: false,
        lang: "en",
      },
      {
        category: "Programming",
        type: "twopart",
        setup: "How do you know God is a shitty programmer?",
        delivery:
          "He wrote the OS for an entire universe, but didn't leave a single useful comment.",
        flags: {
          nsfw: false,
          religious: true,
          political: false,
          racist: false,
          sexist: false,
          explicit: true,
        },
        id: 19,
        safe: false,
        lang: "en",
      },
      {
        category: "Programming",
        type: "single",
        joke: "Your momma is so fat, you need to switch to NTFS to store a picture of her.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 54,
        safe: false,
        lang: "en",
      },
      {
        category: "Programming",
        type: "twopart",
        setup: "What are bits?",
        delivery:
          "Tiny things left when you drop your computer down the stairs.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 210,
        safe: true,
        lang: "en",
      },
      {
        category: "Programming",
        type: "single",
        joke: "Java is like Alzheimer's, it starts off slow, but eventually, your memory is gone.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 27,
        safe: false,
        lang: "en",
      },
      {
        category: "Programming",
        type: "twopart",
        setup: "Why did the database administrator leave his wife?",
        delivery: "She had one-to-many relationships.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        safe: true,
        id: 264,
        lang: "en",
      },
      {
        category: "Dark",
        type: "single",
        joke: "I was going to tell a dead baby joke. But I decided to abort.",
        flags: {
          nsfw: false,
          religious: false,
          political: false,
          racist: false,
          sexist: false,
          explicit: false,
        },
        id: 206,
        safe: false,
        lang: "en",
      },
    ],
  },
];

// 1. Pick a random group (Object 0 or Object 1)
let groupIndex = Math.floor(Math.random() * hello_joke.length);
let selectedGroup = hello_joke[groupIndex];

// 2. Pick a random joke from that specific group's 'jokes' array
let jokeIndex = Math.floor(Math.random() * selectedGroup.jokes.length);
let randomJoke = selectedGroup.jokes[jokeIndex];

// 3. Display it (handling both 'single' and 'twopart' joke types)
if (randomJoke.type === "single") {
  hello.innerHTML = randomJoke.joke;
} else {
  hello.innerHTML = `<strong>${randomJoke.setup}</strong> <br> ${randomJoke.delivery}`;
}
