const jokes = [
  "Why don't skeletons fight each other? They don't have the guts! 💀",
  "What do you call fake spaghetti? An impasta! 🍝",
  "Why did the scarecrow win an award? He was outstanding in his field! 🌾",
  "How does a penguin build its house? Igloos it together! 🐧",
  "Why don't eggs tell jokes? They'd crack each other up! 🥚",
  "What did one wall say to the other? I'll meet you at the corner! 🧱",
  "Why can't you give Elsa a balloon? She'll let it go! 🎈",
  "How do you organize a space party? You planet! 🪐",
  "What do you call a bear with no teeth? A gummy bear! 🐻",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one! ⛳",
  "What did the ocean say to the beach? Nothing, it just waved! 🌊",
  "Why don't programmers like nature? It has too many bugs! 🐛",
  "How do you make a tissue dance? Put a little boogie in it! 🕺",
  "What do you call cheese that isn't yours? Nacho cheese! 🧀",
  "Why did the math book look sad? Because it had too many problems! 📚",

  'Why did the salamander go to Hollywood? 🦎 "To make newt movies!" 🎬',
  'Did you hear the one about the New York Jets cocktail? 🍸 "Two of them, and you forget what Joe Namath." 🏈',
  'Why did the veterinarian prescribe birth-control pills for dogs? 🐶 "It’s part of an anti-litter campaign." 🚯',
  'Why don’t pirates take a shower before they walk the plank? 🏴‍☠️ "They just wash up on shore." 🌊',
  'On what grounds did the police arrest the devil? 👹 "They got him on possession." 👮',
  'How many telemarketers does it take to change a lightbulb? ☎️ "Only one, but he has to do it while you are eating dinner." 🍽️',
  'What did one fish in a tank say to the other fish in the tank? 🐟 "Do you know how to drive this thing?" 🛡️',
  'What do rich people say when they tickle babies? 👶 "Gucci, Gucci, goo." 👜',
  'How many therapists does it take to change a lightbulb? 💡 "Only one, but the lightbulb has to want to change." 🛋️',
  'Why don’t anteaters ever get sick? 🐜 "Their anty-bodies keep them healthy." 🛡️',
  'How many gorillas does it take to change a lightbulb? 🦍 "Just one … but it takes a whole lot of lightbulbs." 💡',
  'Who was the roundest knight in King Arthur’s court? ⚔️ "Sir Cumference." 📏',
  'Why do cemeteries have fences around them? ⚰️ "Because everyone’s dying to get in." 🪦',
  'How many optometrists does it take to change a lightbulb? 👓 "Is it one or two? One … or two?" 💡',
  'What do you give a man who has everything? 🎁 "Penicillin." 💊',
  'What kind of felines can bowl? 🎳 "Alley cats." 🐱',
  'Why did the man bring his watch to the bank? ⌚ "He wanted to save time." 🏦',
  'What’s the difference between a hippo and a Zippo? 🦛 "One weighs a ton, and the other is a little lighter." 🔥',
  'Did you hear about the guy who got the left side of his body amputated? 🩼 "He’s all right now." 😄',
  'What do you call a fake dad? 👨 "A faux pas." 😏',
  'Why do dogs float in water? 🐕 "Because they’re good buoys." 🚣‍♂️',
  'What should you do if your puppy isn’t feeling well? 🐶 "Take him to the dog-tor." 🩺',
  'Why couldn’t the lifeguard rescue the hippie? 🏖️ "Because he was too far out, man." ✌️',
  'Where do penguins go to vote? 🐧 "The North Poll." 🗳️',
  'What do you call a girl with no eyes? 👧 "A grl." 😆',
  'Where do birds stay when they travel? 🐦 "Someplace cheep." 🏨',
  'Why should you knock on your refrigerator door before opening it? 🥗 "There may be salad dressing in there." 🥬',
  'Did you hear about the worst zoo in the world? 🐕 "It only has one dog. It’s a real shih tzu." 🏞️',
  'What did one toilet say to the other? 🚽 "You appear a bit flushed." 😳',
  'Why are most people tired on April 1? 📅 "They’ve just finished a 31-day March." 🥱',
  'How do you make a tissue dance? 🧻 "Put a little boogie in it." 🕺',
  'Why aren’t lobsters generous? 🦞 "Because they’re shellfish." 🤑',
  'Why did Mozart kill all of his chickens? 🎼 "When he asked who the best composer was, they all replied, “Bach, Bach, Bach.”" 🐔',
  'Why did the rabbit go to the salon? 🐰 "It was having a bad hare day." 💇‍♀️',
  'Why can’t leopards play hide-and-seek? 🐆 "Because they’re always spotted." 🕵️‍♂️',
  'How do you light up a sports stadium? ⚽ "With a soccer match." 🏟️',
  'Where do sheep love to vacation? 🐑 "The Baa-hamas." 🏝️',
  'Why do historians call the Early Middle Ages the Dark Ages? ⚔️ "There were a lot of knights." 🌙',
  'Why did the employee go work on stilts? 🏢 "He wanted a raise." 🦯',
  'What did one plate say to the other? 🍽️ "Lunch is on me!" 😄',
  'Why do comedians love telling jokes to ducks? 🦆 "They always quack up." 😂',
  'How did the piano get locked out of its car? 🎹 "It lost its keys." 🔑',
  'What do you call a nose without a body? 👃 "No body nose." 🤷‍♂️',
  'How do you make an egg roll? 🥚 "You push it." 👐',
  'Did you hear about the fire at the shoe factory? 👟 "Unfortunately, many soles were lost." 🔥',
  'What kind of fish knows how to do an appendectomy? 🐟 "A sturgeon." 🩺',
  'How do you hire a horse? 🐴 "Stand it on a ladder." 🪜',
  'What did the fish say when he ran into a wall in the river? 🐠 "Dam!" 🦫',
  'Why do giraffes have long necks? 🦒 "Because they have stinky feet." 🦶😷',
  'Why did the pony ask for a glass of water? 🐴 "Because it was a little horse." 🥀',
  'Is there anything worse than when it’s raining cats and dogs? 🌧️ "Yes, hailing taxis." 🚕',
  'What do you call two doctors? 👨‍⚕️👩‍⚕️ "Pair-a-medics." 🚑',
  'What did 0 say to 8? 🔢 "Nice belt." 😎',
  'My mom died when we couldn’t remember her blood type. 🩸 "The last thing she said was, ‘Be positive.’ But it’s hard without her." 😢',
  'I wondered why the baseball kept getting bigger. ⚾ "Then it hit me." 💥',
  'While digging in the garden, I found a chest full of gold coins. 🏴‍☠️ "I wanted to tell my wife about it, but then I remembered why I was digging in our garden." 🪦',
  'Today at the bank, an old lady asked me to help check her balance. 🏦 "So I pushed her over." 👵💥',
  'I childproofed my house. 🔒 "Somehow they still got in!" 👶😈',
  'Cremation. 🔥 "My final hope for a smokin’ hot body." 😏',
  'Before my friend Frank died, he asked that I store his ashes in his favorite beer mug. 🍺 "His last wish was to be Frank in stein." ⚱️',
  'A man walks into an enchanted forest and tries to cut down a talking tree. 🌳 "‘You can’t cut me down,’ the tree exclaims. ‘I’m a talking tree!’ The man responds, ‘You may be a talking tree, but you will dialogue.’" 🪓',
  'Today, I asked my phone, ‘Siri, why am I still single?’ 📱 "It activated the front-facing camera." 🤳😭',
  'Even people who are good for nothing have the capacity to bring a smile to your face. 😄 "Like when you push them down the stairs." 🌀',
  'My husband and I have reached the difficult decision that we do not want children. 👨‍👩‍👧‍👦 "If anybody does, please just send me your contact details, and we can drop them off tomorrow." 🚗',
  'The most corrupt CEOs are the ones who run pretzel companies. 🥨 "They’re always so twisted." 😈',
  'You’re not completely useless. 🫵 "You can always be used as a bad example." 📛',
  'Never break someone’s heart. ❤️ "They only have one of those. Break their bones instead—they have 206 of them." 🦴',
  'My grandma has the heart of a lion 🦁 "and a lifetime ban from the zoo." 🚫🧓',
  'After the man who created the hokeypokey died, it took a while to get the body in the casket. ⚰️ "They put his right foot in. They took his right foot out…." 🕺',
  'When I told my date I worked with animals, she found it really sweet and asked more about my job. 🥩 "So I told her: ‘I’m a butcher.’" 🔪',
  'They say the surest way to a man’s heart is through the stomach. 🍽️ "But I find going through the rib cage a lot easier." 🗡️',
  'Why is it that if you donate a kidney, people love you, 🫀 "but if you donate five kidneys, they call the police?" 🚔',
  'Two cows were standing in a field. 🐄 "‘Have you heard that mad cow disease is going around?’ asked the first. ‘Yeah,’ the other cow replied. ‘Makes me glad I’m a penguin.’" 🐧',
  'At a party, a woman admonished her husband, saying, 🍰 "‘That’s the fourth time you’ve gone back for ice cream and cake. Doesn’t it embarrass you?’ He shrugged and answered, ‘Why should it? I keep telling them it’s for you.’" 😏',
  '‘Your mother has been with us for 20 years,’ said John. 👵 "‘Isn’t it time she got a place of her own?’ Helen’s brow furrowed, and she replied, ‘I thought she was your mother.’" 😲',
  '‘I’d like a bottle of wine,’ a woman told her waiter. 🍷 "‘What year, ma’am?’ the waiter replied. She huffed and said, ‘Well, I’d like it right now.’" ⏰',
  'Yesterday, I couldn’t figure out whether someone was waving at me or the person behind me. 👋 "In other news, I lost my lifeguarding job." 🏊‍♂️🚫',
  'A bear walks into a bar and says, 🐻 "‘Can I have a … Coke?’ The bartender asks, ‘What’s with the big pause?’ The bear replies, ‘I don’t know. I was born with them.’" 🐾',
  '‘My son had to give up his career because of fallen arches,’ said a man to his friend. 🏗️ "‘He’s an athlete?’ the friend asked. The man shook his head and replied, ‘An architect.’" 😆',
  'A man dining at a seafood restaurant asked for a lobster tail. 🦞 "The waitress smiled sweetly and said, ‘Once upon a time, there was this lobster …’" 📖',
  'Give a man a fish, and he will eat for a day. 🐟 "Teach a man to fish, and he will sit in a boat and drink beer all day." 🍺⛵',
  'A man went to see his doctor, and the doctor said, 🩺 "‘I have some bad news and some worse news.’ The man asked for the bad news first, and the doctor replied, ‘You have only 24 hours to live.’ Gutted, the man said, ‘That’s terrible! Wait a minute—what’s the worse news?’ The doctor responded, ‘I should have told you yesterday.’" 😱',
];

function tellJoke() {
  const jokeElement = document.getElementById("joke");

  // Pick a random joke
  const randomIndex = Math.floor(Math.random() * jokes.length);
  const newJoke = jokes[randomIndex];

  // Add a little animation
  jokeElement.style.opacity = 0;

  setTimeout(() => {
    jokeElement.textContent = newJoke;
    jokeElement.style.opacity = 1;
  }, 300);
}

// Optional: Show a joke immediately when page loads
window.onload = tellJoke;
